
version: 2

sources:
  - name: company_info
    database: cedar-style-412618
    schema: job_postings_project

    tables:
       - name: companies
       - name: employee_counts
       

  - name: industry
    database: cedar-style-412618
    schema: job_postings_project 
     
    tables:
       - name: job_industries

  - name: skills
    database: cedar-style-412618
    schema: job_postings_project 
     
    tables:
       - name: job_skills

  - name: fact
    database: cedar-style-412618
    schema: job_postings_linkedin 
     
    tables:
       - name: job_postings
    

